### ISSUE TITLE
docker-compose, certificates

### ISSUE THREAD

**Issue by ThomasPfuhl** [DINA-Web/keycloak-docker#2]
I followed the instructions for local development. My config:
Ubuntu 16.04, Docker version 1.13.1 build 092cba3, docker-compose version 1.8.0, build unknown.

The shipped file  `docker-compose.yml`  has the line  " version: '3.1' ", which I had to change to version: '2' in order to make it work. Otherwise I get an "unsupported" error message.
 
`make create-certs` does not create a file `ca.pem` but the files `certs/dina-web.local.[crt|key]`. Hence I do not know how to import the authority file into the browser.

`make up` works and starts a http-proxy on port 8080. Hence the keycloak URL is  `http://keycloak.accounts.dina-web.local:8080` which works fine for creating realms and accounts.

**Comment by mskyttner** [comment]
@Inkimar asked me to comment on this:

This link https://docs.docker.com/compose/compose-file/compose-versioning/#versioning says that version 3+ is "recommended" and it requires Docker engine 1.13.1+ and Docker Compose version 1.10.0, so I guess it means that if you upgrade the docker-compose tool the "unsupported" should go away...

I think `make create-certs` does create a `ca.pem` file under the `/tmp` directory due to the volume mount happening here: https://github.com/DINA-Web/keycloak-docker/blob/master/Makefile#L16

However, it is not copied into any directory under where the `docker-compose.yml` file location so the file risks being lost after restarting the host (or whenever when the /tmp directory is emptied by the system, I think it may happen on a laptop restart for example). The Makefile could be adjusted to stash away the ca.pem file at a better location and some docs like these https://github.com/bioatlas/zoa-docker#self-signed-certs could be used to update the README to provide a link to how the ca.pem-installation can be done. 

PR, anyone?

**Comment by ThomasPfuhl** [comment]
I installed docker-compose 1.18 from github. Now, version 3.1 in the `docker-compose.yml` file  is accepted.

Indeed,  the file `/tmp/ca.pem` is created. Then I followed the instructions in
[https://thomas-leister.de/en/how-to-import-ca-root-certificate](https://thomas-leister.de/en/how-to-import-ca-root-certificate)/
